[build]
builder = "NIXPACKS"

[deploy]
numReplicas = 1
startCommand = "gunicorn studybuddy.wsgi:application --bind=0.0.0.0:8000"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 1

[networking]
port = 8000
